[package]
name = "hilltop_clients"
version = "0.1.0"
authors = ["rbuckley"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
date_time = "2.1.0"
